In [29]:
import numpy as np

In [30]:
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

In [31]:
inputs.shape

(4, 2)

In [32]:
outputs = np.array([0, 0, 0, 1])

In [33]:
outputs.shape

(4,)

In [34]:
weights = np.array([0.0, 0.0])

In [35]:
learning_rate = 0.1

In [36]:
def step_function(sum):
    if (sum >= 1):
        return 1
    else:
        return 0

In [37]:
def cal_output(instance):
    sum_func = instance.dot(weights)
    return step_function(sum_func)

In [38]:
cal_output(np.array([[1,1]]))

0

In [39]:
len(outputs)

4

In [40]:
inputs[3]

array([1, 1])

In [41]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [42]:
def train():
    total_error_value = 1
    while (total_error_value != 0):
        total_error_value = 0
        for i in range(len(outputs)):
            prediction = cal_output(inputs[i])
            error = abs(outputs[i] - prediction)
            total_error_value += error
            if error > 0:
                for j in range(len(weights)):
                    weights[j] = weights[j] + (learning_rate*inputs[i][j]*error)
                    print('Weight updated to: ' + str(weights[j]))
        print('Total error Value: ' + str(total_error_value))

In [43]:
train()

Weight updated to: 0.1
Weight updated to: 0.1
Total error Value: 1
Weight updated to: 0.2
Weight updated to: 0.2
Total error Value: 1
Weight updated to: 0.30000000000000004
Weight updated to: 0.30000000000000004
Total error Value: 1
Weight updated to: 0.4
Weight updated to: 0.4
Total error Value: 1
Weight updated to: 0.5
Weight updated to: 0.5
Total error Value: 1
Total error Value: 0


In [44]:
weights

array([0.5, 0.5])